In [1]:
from outbreak_data import outbreak_data
from outbreak_data.authenticate_user import set_authentication


outbreak_data.print_reqs = True

In [2]:
import auth_token

from outbreak_data.authenticate_user import set_authentication
set_authentication(auth_token.get_auth_token())

In [3]:
outbreak_data.wildcard_mutations('s:e484*')

GET https://api.outbreak.info/genomics/mutation-details?mutations=s:e484*

,type,gene,ref_codon,pos,alt_codon,is_synonymous,ref_aa,codon_num,alt_aa
mutation,,,,,,,,,
S:E484L,substitution,S,GAA,23012,CTT,False,E,484,L
S:E484A,substitution,S,GAA,23013,GCC,False,E,484,A
S:E484R,substitution,S,GAA,23012,AGG,False,E,484,R
S:E484V,substitution,S,GAA,23012,GTG,False,E,484,V
S:E484T,substitution,S,GAA,23012,ACA,False,E,484,T
S:E484D,substitution,S,GAA,23012,GAC,False,E,484,D
S:E484H,substitution,S,GAA,23013,CAT,False,E,484,H
S:E484K,substitution,S,GAA,23013,AAG,False,E,484,K
S:E484Q,substitution,S,GAA,23011,CAA,False,E,484,Q
S:E484I,substitution,S,GAA,23011,ATA,False,E,484,I

In [4]:
outbreak_data.wildcard_lineage('*.86.*')

GET https://api.outbreak.info/genomics/lineage?name=*.86.*

           total_count
name
ba.2.86.1        11102
ba.2.86.3          380
ba.2.86.2          328
ba.2.86.5           38
ba.2.86.4           10
ba.2.86.6            9
ba.2.86.7            2

In [5]:
outbreak_data.wildcard_location('*awai*')

GET https://api.outbreak.info/genomics/location?name=*awai*

,country,country_id,division,division_id,label,admin_level,total_count,location,location_id
id,,,,,,,,,
USA_US-HI,United States,USA,Hawaii,HI,"Hawaii, United States",1,29240,NaN,NaN
USA_US-HI_15001,United States,USA,Hawaii,HI,"Hawaii, Hawaii, United States",2,3388,Hawaii,15001
IND_IN-RJ_SM,India,IND,Rajasthan,RJ,"Sawai Madhopur, Rajasthan, India",2,138,Sawai Madhopur,SM

In [6]:
print(outbreak_data.cases_by_location(['USA_US-HI', 'USA_US-KY'], 2))

GET https://api.outbreak.info/covid19/query?q=location_id:(USA_US-HI OR USA_US-KY)&sort=date&fields=date,admin1,confirmed_numIncrease, confirmed_rolling&fetch_all=true
GET https://api.outbreak.info/covid19/query?scroll_id=FGluY2x1ZGVfY29udGV4dF91dWlkDnF1ZXJ5VGhlbkZldGNoAxZwckRwT2p5NFFSYVM0d01HZWt0Z0d3AAAAAAszWH4WU3RpUXZHU0ZSaldScGhPSGRUME1tdxZmU1FLVi10M1NKdWdqN3VVQUtLLTFBAAAAAAwJXXEWc0hMeURPR1VUMW1PTlZ1cUxwVXBTURZKcXVNTUIya1JDR0FvOFhGQWxMakJ3AAAAAA-FVZoWUmFoc1VXdGlRX1dJMk9OTDktVFFfdw==&fetch_all=true&page=0&fetch_all=true
GET https://api.outbreak.info/covid19/query?scroll_id=FGluY2x1ZGVfY29udGV4dF91dWlkDnF1ZXJ5VGhlbkZldGNoAxZwckRwT2p5NFFSYVM0d01HZWt0Z0d3AAAAAAszWH4WU3RpUXZHU0ZSaldScGhPSGRUME1tdxZmU1FLVi10M1NKdWdqN3VVQUtLLTFBAAAAAAwJXXEWc0hMeURPR1VUMW1PTlZ1cUxwVXBTURZKcXVNTUIya1JDR0FvOFhGQWxMakJ3AAAAAA-FVZoWUmFoc1VXdGlRX1dJMk9OTDktVFFfdw==&fetch_all=true&page=1&fetch_all=true
GET https://api.outbreak.info/covid19/query?scroll_id=FGluY2x1ZGVfY29udGV4dF91dWlkDnF1ZXJ5VGhlbkZldGNoAxZwckRwT2p5NFFSYVM0d01HZWt0Z0d3AAAAAAszWH4WU3RpUXZHU0ZSaldScGhPSGRUME1tdxZmU1FLVi10M1NKdWdqN3VVQUtLLTFBAAAAAAwJXXEWc0hMeURPR1VUMW1PTlZ1cUxwVXBTURZKcXVNTUIya1JDR0FvOFhGQWxMakJ3AAAAAA-FVZoWUmFoc1VXdGlRX1dJMk9OTDktVFFfdw==&fetch_all=true&page=2&fetch_all=true
                              confirmed_numIncrease  confirmed_rolling
location          date
USA_Hawaii_None   2020-02-12                      0           0.000000
                  2020-02-13                      0           0.000000
                  2020-02-14                      0           0.000000
                  2020-02-15                      0           0.000000
                  2020-02-16                      0           0.000000
...                                             ...                ...
USA_Kentucky_None 2023-03-04                      0         748.857117
                  2023-03-05                      0         748.857117
                  2023-03-06                      0          66.285713
                  2023-03-07                      0          66.285713
                  2023-03-08                   4787         750.142883

[2242 rows x 2 columns]

In [7]:
outbreak_data.most_recent_cl_data('ba.2.86.1', location='USA_US-HI')

GET https://api.outbreak.info/genomics/most-recent-collection-date-by-location?pangolin_lineage=ba.2.86.1&location_id=USA_US-HI

Timestamp('2024-01-04 00:00:00')

In [8]:
outbreak_data.daily_lag(location='USA_US-HI')

GET https://api.outbreak.info/genomics/collection-submission?location_id=USA_US-HI

                               total_count
date_collected date_submitted
2020-03-05     2020-04-16                1
2020-03-07     2020-04-16                1
2020-03-11     2020-12-31                1
2020-03-12     2020-06-16                2
               2020-12-31                1
...                                    ...
2024-06-24     2024-07-24                6
2024-06-25     2024-07-06                5
               2024-07-24                4
2024-06-26     2024-07-06                9
2024-06-27     2024-07-06                1

[5931 rows x 1 columns]

In [9]:
outbreak_data.sequence_counts('USA_US-HI', sub_admin=True)

GET https://api.outbreak.info/genomics/sequence-count?&cumulative=true&subadmin=true&location_id=USA_US-HI

                 total_count
location_id
USA_US-HI_15003        14628
USA_US-HI_15009         3693
USA_US-HI_15001         3388
USA_US-HI_15007          857
USA_US-HI_15005            3

In [10]:
outbreak_data.sequence_counts('USA_US-HI')

GET https://api.outbreak.info/genomics/sequence-count?&cumulative=false&subadmin=false&location_id=USA_US-HI

            total_count
date
2020-03-05            1
2020-03-07            1
2020-03-11            1
2020-03-12            3
2020-03-13            1
...                 ...
2024-06-23            6
2024-06-24           11
2024-06-25            9
2024-06-26            9
2024-06-27            1

[1409 rows x 1 columns]

In [11]:
outbreak_data.known_mutations('BA.2.86.1', descendants=True)

GET https://api.outbreak.info/genomics/lineage-mutations?lineages=None&q=pangolin_lineage_crumbs:*;BA.2.86.1;*&frequency=0.8

,mutation_count,lineage_count,lineage,gene,ref_aa,alt_aa,codon_num,codon_end,type,prevalence,change_length_nt
mutation,,,,,,,,,,,
orf1b:r1315c,11086,11102,pangolin_lineage_crumbs:*;BA.2.86.1;*,ORF1b,R,C,1315,NaN,substitution,0.998559,NaN
orf1b:p314l,11077,11102,pangolin_lineage_crumbs:*;BA.2.86.1;*,ORF1b,P,L,314,NaN,substitution,0.997748,NaN
orf1a:p3395h,11073,11102,pangolin_lineage_crumbs:*;BA.2.86.1;*,ORF1a,P,H,3395,NaN,substitution,0.997388,NaN
e:t9i,11065,11102,pangolin_lineage_crumbs:*;BA.2.86.1;*,E,T,I,9,NaN,substitution,0.996667,NaN
s:a570v,11060,11102,pangolin_lineage_crumbs:*;BA.2.86.1;*,S,A,V,570,NaN,substitution,0.996217,NaN
...,...,...,...,...,...,...,...,...,...,...,...
m:t30a,9513,11102,pangolin_lineage_crumbs:*;BA.2.86.1;*,M,T,A,30,NaN,substitution,0.856873,NaN
s:r21t,9440,11102,pangolin_lineage_crumbs:*;BA.2.86.1;*,S,R,T,21,NaN,substitution,0.850297,NaN
s:r403k,9145,11102,pangolin_lineage_crumbs:*;BA.2.86.1;*,S,R,K,403,NaN,substitution,0.823725,NaN
s:del25/27,9100,11102,pangolin_lineage_crumbs:*;BA.2.86.1;*,S,S:DEL25/27,DEL25/27,25,27.0,deletion,0.819672,9.0
s:l24s,9083,11102,pangolin_lineage_crumbs:*;BA.2.86.1;*,S,L,S,24,NaN,substitution,0.818141,NaN

In [12]:
outbreak_data.known_mutations(['BA.1', 'BA.2'])

GET https://api.outbreak.info/genomics/lineage-mutations?pangolin_lineage=BA.1 OR BA.2&frequency=0.8

,mutation_count,lineage_count,lineage,gene,ref_aa,alt_aa,codon_num,codon_end,type,prevalence,change_length_nt
mutation,,,,,,,,,,,
s:d614g,1655466,1658956,BA.1 OR BA.2,S,D,G,614,NaN,substitution,0.997896,NaN
s:h655y,1653886,1658956,BA.1 OR BA.2,S,H,Y,655,NaN,substitution,0.996944,NaN
orf1b:p314l,1652461,1658956,BA.1 OR BA.2,ORF1b,P,L,314,NaN,substitution,0.996085,NaN
s:n679k,1651160,1658956,BA.1 OR BA.2,S,N,K,679,NaN,substitution,0.995301,NaN
s:n969k,1648457,1658956,BA.1 OR BA.2,S,N,K,969,NaN,substitution,0.993671,NaN
orf1a:p3395h,1647910,1658956,BA.1 OR BA.2,ORF1a,P,H,3395,NaN,substitution,0.993342,NaN
s:q954h,1647096,1658956,BA.1 OR BA.2,S,Q,H,954,NaN,substitution,0.992851,NaN
s:p681h,1645287,1658956,BA.1 OR BA.2,S,P,H,681,NaN,substitution,0.991760,NaN
orf1a:t3255i,1645155,1658956,BA.1 OR BA.2,ORF1a,T,I,3255,NaN,substitution,0.991681,NaN
e:t9i,1643531,1658956,BA.1 OR BA.2,E,T,I,9,NaN,substitution,0.990702,NaN
s:d796y,1637348,1658956,BA.1 OR BA.2,S,D,Y,796,NaN,substitution,0.986975,NaN
m:a63t,1633388,1658956,BA.1 OR BA.2,M,A,T,63,NaN,substitution,0.984588,NaN
n:p13l,1631079,1658956,BA.1 OR BA.2,N,P,L,13,NaN,substitution,0.983196,NaN
orf8:s84l,1622046,1658956,BA.1 OR BA.2,ORF8,S,L,84,NaN,substitution,0.977751,NaN
n:g204r,1614716,1658956,BA.1 OR BA.2,N,G,R,204,NaN,substitution,0.973333,NaN
n:r203k,1612948,1658956,BA.1 OR BA.2,N,R,K,203,NaN,substitution,0.972267,NaN
orf1b:i1566v,1605878,1658956,BA.1 OR BA.2,ORF1b,I,V,1566,NaN,substitution,0.968005,NaN
s:g142d,1599793,1658956,BA.1 OR BA.2,S,G,D,142,NaN,substitution,0.964337,NaN
s:g339d,1587670,1658956,BA.1 OR BA.2,S,G,D,339,NaN,substitution,0.957030,NaN
n:del31/33,1571408,1658956,BA.1 OR BA.2,N,N:DEL31/33,DEL31/33,31,33.0,deletion,0.947227,9.0
s:n764k,1566209,1658956,BA.1 OR BA.2,S,N,K,764,NaN,substitution,0.944093,NaN
m:q19e,1554301,1658956,BA.1 OR BA.2,M,Q,E,19,NaN,substitution,0.936915,NaN
s:s373p,1552833,1658956,BA.1 OR BA.2,S,S,P,373,NaN,substitution,0.936030,NaN
s:s375f,1547620,1658956,BA.1 OR BA.2,S,S,F,375,NaN,substitution,0.932888,NaN
s:t478k,1529864,1658956,BA.1 OR BA.2,S,T,K,478,NaN,substitution,0.922185,NaN
s:e484a,1527499,1658956,BA.1 OR BA.2,S,E,A,484,NaN,substitution,0.920759,NaN
s:s477n,1526772,1658956,BA.1 OR BA.2,S,S,N,477,NaN,substitution,0.920321,NaN
s:q493r,1503701,1658956,BA.1 OR BA.2,S,Q,R,493,NaN,substitution,0.906414,NaN
s:n501y,1487262,1658956,BA.1 OR BA.2,S,N,Y,501,NaN,substitution,0.896505,NaN
s:y505h,1487157,1658956,BA.1 OR BA.2,S,Y,H,505,NaN,substitution,0.896441,NaN
s:q498r,1481869,1658956,BA.1 OR BA.2,S,Q,R,498,NaN,substitution,0.893254,NaN
s:k417n,1416780,1658956,BA.1 OR BA.2,S,K,N,417,NaN,substitution,0.854019,NaN
s:n440k,1328501,1658956,BA.1 OR BA.2,S,N,K,440,NaN,substitution,0.800805,NaN

In [13]:
outbreak_data.mutation_prevalences(['orf1b:r1315c', 's:l24s'], pango_lin='BA.2')

GET https://api.outbreak.info/genomics/mutations-by-lineage?mutations=orf1b:r1315c, s:l24s&pangolin_lineage=BA.2

,pangolin_lineage,lineage_count,mutation_count,proportion,proportion_ci_lower,proportion_ci_upper
query,,,,,,
s:l24s,ba.2,1224388,1143593,0.934012,0.933571,0.934451
orf1b:r1315c,ba.2,1224388,1218961,0.995568,0.995449,0.995684

In [14]:
outbreak_data.lineage_cl_prevalence('BA.2.86.1', descendants=True)

GET https://api.outbreak.info/genomics/prevalence-by-location?lineages=None&q=pangolin_lineage_crumbs:*;BA.2.86.1;*&cumulative=false

,,total_count,lineage_count,total_count_rolling,lineage_count_rolling,proportion,proportion_ci_lower,proportion_ci_upper
date,query,,,,,,,
2023-01-17,pangolin_lineage_crumbs:*;BA.2.86.1;*,7437,1,6705.571429,0.142857,0.000021,7.322043e-08,0.000374
2023-01-18,pangolin_lineage_crumbs:*;BA.2.86.1;*,6992,0,6533.285714,0.142857,0.000022,7.515931e-08,0.000384
2023-01-19,pangolin_lineage_crumbs:*;BA.2.86.1;*,5746,0,6343.428571,0.142857,0.000023,7.741056e-08,0.000396
2023-01-20,pangolin_lineage_crumbs:*;BA.2.86.1;*,5145,0,6100.285714,0.142857,0.000023,8.049417e-08,0.000412
2023-01-21,pangolin_lineage_crumbs:*;BA.2.86.1;*,3359,0,5995.714286,0.142857,0.000024,8.189027e-08,0.000419
...,...,...,...,...,...,...,...,...
2024-07-19,pangolin_lineage_crumbs:*;BA.2.86.1;*,13,0,113.857143,0.000000,0.000000,4.297876e-06,0.021746
2024-07-20,pangolin_lineage_crumbs:*;BA.2.86.1;*,10,0,88.142857,0.000000,0.000000,5.564093e-06,0.028062
2024-07-21,pangolin_lineage_crumbs:*;BA.2.86.1;*,5,0,63.571429,0.000000,0.000000,7.642474e-06,0.038341
2024-07-22,pangolin_lineage_crumbs:*;BA.2.86.1;*,26,0,31.714286,0.000000,0.000000,1.522530e-05,0.074928
2024-07-23,pangolin_lineage_crumbs:*;BA.2.86.1;*,1,0,16.714286,0.000000,0.000000,2.846238e-05,0.135478

In [15]:
outbreak_data.lineage_cl_prevalence('BA.2.86.1', descendants=True, datemin='2023-06-01', datemax='2024-01-01')

GET https://api.outbreak.info/genomics/prevalence-by-location?lineages=None&q=pangolin_lineage_crumbs:*;BA.2.86.1;*&cumulative=false&min_date=2023-06-01&max_date=2024-01-01

,,total_count,lineage_count,total_count_rolling,lineage_count_rolling,proportion,proportion_ci_lower,proportion_ci_upper
date,query,,,,,,,
2023-08-17,pangolin_lineage_crumbs:*;BA.2.86.1;*,2668,1,2474.000000,0.142857,0.000058,1.984579e-07,0.001015
2023-08-18,pangolin_lineage_crumbs:*;BA.2.86.1;*,2486,0,2525.000000,0.142857,0.000057,1.944499e-07,0.000994
2023-08-19,pangolin_lineage_crumbs:*;BA.2.86.1;*,1569,0,2516.571429,0.142857,0.000057,1.950678e-07,0.000997
2023-08-20,pangolin_lineage_crumbs:*;BA.2.86.1;*,1482,1,2510.000000,0.285714,0.000114,1.956118e-07,0.001000
2023-08-21,pangolin_lineage_crumbs:*;BA.2.86.1;*,4740,0,2656.857143,0.285714,0.000108,1.847905e-07,0.000945
...,...,...,...,...,...,...,...,...
2023-12-28,pangolin_lineage_crumbs:*;BA.2.86.1;*,3339,97,2580.000000,84.857143,0.032890,2.657294e-02,0.040365
2023-12-29,pangolin_lineage_crumbs:*;BA.2.86.1;*,2875,69,2637.142857,84.142857,0.031907,2.565631e-02,0.039079
2023-12-30,pangolin_lineage_crumbs:*;BA.2.86.1;*,1757,37,2648.857143,81.714286,0.030849,2.486268e-02,0.038071
2023-12-31,pangolin_lineage_crumbs:*;BA.2.86.1;*,1584,49,2681.000000,81.857143,0.030532,2.456503e-02,0.037619
2024-01-01,pangolin_lineage_crumbs:*;BA.2.86.1;*,2210,76,2700.142857,78.428571,0.029046,2.306633e-02,0.035720

In [16]:
outbreak_data.lineage_cl_prevalence(['BA.2.86.1', 'XBB.1.5'], cumulative=True)

GET https://api.outbreak.info/genomics/prevalence-by-location?pangolin_lineage=BA.2.86.1,XBB.1.5&cumulative=true

                    BA.2.86.1     XBB.1.5
global_prevalence    0.008392    0.049024
total_count           1322849     3885651
lineage_count           11102      190491
first_detected     2023-01-17  2022-06-12
last_detected      2024-06-28  2024-01-14

In [17]:
outbreak_data.lineage_by_sub_admin(['BA.1', 'BA.2'], location='USA')

GET https://api.outbreak.info/genomics/lineage-by-sub-admin-most-recent?pangolin_lineage=BA.1,BA.2&location_id=USA&ndays=180&detected=false

,,date,id,total_count,lineage_count,cum_total_count,cum_lineage_count,proportion,proportion_ci_lower,proportion_ci_upper
name,query,,,,,,,,,
,BA.2,2024-02-15,USA_US-None,1,0,1,0,0.0,3.855810e-04,0.853254
Alabama,BA.2,2024-05-06,USA_US-AL,3,0,19,0,0.0,2.550581e-05,0.122309
Alaska,BA.2,2024-06-10,USA_US-AK,1,0,9,0,0.0,5.306405e-05,0.237610
Arizona,BA.2,2024-07-10,USA_US-AZ,3,0,653,0,0.0,7.516790e-07,0.003838
Arkansas,BA.2,2024-05-08,USA_US-AR,1,0,25,0,0.0,1.944577e-05,0.094683
...,...,...,...,...,...,...,...,...,...,...
Virginia,BA.1,2024-07-15,USA_US-VA,1,0,1771,0,0.0,2.772248e-07,0.001417
Washington,BA.1,2024-07-13,USA_US-WA,3,0,932,0,0.0,5.267197e-07,0.002691
West Virginia,BA.1,2024-05-28,USA_US-WV,1,0,17,0,0.0,2.846238e-05,0.135478
Wisconsin,BA.1,2024-04-08,USA_US-WI,1,0,604,0,0.0,8.126344e-07,0.004148
Wyoming,BA.1,2024-06-29,USA_US-WY,2,0,26,0,0.0,1.870506e-05,0.091247

In [18]:
outbreak_data.all_lineage_prevalences('USA_US-HI')

GET https://api.outbreak.info/genomics/prevalence-by-location-all-lineages?location_id=USA_US-HI&ndays=180&nday_threshold=10&other_threshold=0.05&cumulative=false

                    total_count  lineage_count  prevalence  prevalence_rolling
date       lineage
2023-10-25 JN.1              15              1    0.066667            0.081395
2023-10-26 JN.1               0              0    0.000000            0.040462
2023-10-27 JN.1               0              0    0.000000            0.029412
2023-10-28 JN.1               0              0    0.000000            0.023102
2023-10-29 JN.1               0              0    0.000000            0.018568
...                         ...            ...         ...                 ...
2024-06-22 OTHER              0              0    0.000000            0.325000
2024-06-23 OTHER              6              3    0.500000            0.340909
2024-06-24 OTHER             11              3    0.272727            0.377778
2024-06-25 OTHER              9              6    0.666667            0.470588
2024-06-26 OTHER              9              4    0.444444            0.531250

[2910 rows x 4 columns]

In [19]:
outbreak_data.all_lineage_prevalences(cumulative=True)

GET https://api.outbreak.info/genomics/prevalence-by-location-all-lineages?ndays=180&nday_threshold=10&other_threshold=0.05&cumulative=true

          total_count  lineage_count  prevalence
lineage
JN.1         15357624         123395    0.008035
JN.1.4       15357624          19798    0.001289
JN.1.7       15357624           6036    0.000393
KP.2         15357624           5195    0.000338
KP.2.3       15357624           5089    0.000331
KP.3         15357624           4433    0.000289
KP.3.1       15357624           4284    0.000279
KP.3.1.1     15357624           4505    0.000293
KP.3.3       15357624           4946    0.000322
OTHER        15357624       15179943    0.988430

In [20]:
outbreak_data.growth_rates(['XBB.1.5', 'BA.2.86'], ['Global', 'USA'])

GET https://api.outbreak.info/growth_rate/query?q=lineage:(XBB.1.5 OR BA.2.86) AND location:(Global OR USA)

                                  G_7  G_7_linear  N_7  N_prev_7  \
location lineage date
USA      BA.2.86 2024-02-29  0.024959    2.527340  0.0       0.0
                 2024-03-01  0.024406    2.470598  0.0       0.0
                 2024-03-02  0.020934    2.115472  1.0       0.0
                 2024-03-03  0.021579    2.181327  1.0       0.0
                 2024-03-04  0.021572    2.180641  1.0       0.0
                 2024-03-05  0.028685    2.910068  1.0       0.0
                 2024-03-06  0.027186    2.755924  1.0       0.0
                 2024-03-07  0.024448    2.474953  1.0       0.0
                 2024-03-08  0.020809    2.102669  2.0       0.0
                 2024-03-09  0.019952    2.015270  1.0       1.0
                 2024-03-10  0.014910    1.502211  1.0       1.0
                 2024-03-11  0.016121    1.625203  1.0       1.0
Global   BA.2.86 2024-02-29  0.016935    1.707912  4.0       3.0
                 2024-03-01  0.016300    1.643322  4.0       4.0
                 2024-03-02  0.012657    1.273729  5.0       4.0
                 2024-03-03 -0.006500   -0.647888  4.0       5.0
                 2024-03-04 -0.009259   -0.921611  4.0       5.0
                 2024-03-05 -0.002926   -0.292176  4.0       6.0
                 2024-03-06 -0.013724   -1.363071  5.0       6.0
                 2024-03-07 -0.014613   -1.450723  5.0       4.0
                 2024-03-08 -0.014287   -1.418562  5.0       4.0
                 2024-03-09 -0.004983   -0.497089  4.0       5.0
                 2024-03-10  0.001706    0.170792  4.0       4.0
                 2024-03-11  0.006146    0.616487  4.0       4.0
                 2024-03-12  0.001849    0.185090  5.0       4.0
                 2024-03-13  0.012980    1.306510  4.0       5.0
                 2024-03-14  0.010987    1.104746  4.0       5.0
                 2024-03-15  0.018807    1.898547  3.0       5.0
                 2024-03-16  0.016059    1.618827  2.0       4.0
                 2024-03-17  0.012148    1.222167  2.0       4.0
                 2024-03-18  0.010745    1.080309  2.0       4.0
                 2024-03-19  0.009617    0.966329  1.0       5.0
                 2024-03-20  0.010643    1.069947  1.0       4.0
                 2024-03-21  0.012719    1.280064  1.0       4.0
                 2024-03-22  0.007665    0.769470  1.0       3.0
                 2024-03-23  0.009628    0.967498  1.0       2.0
                 2024-03-24  0.015924    1.605172  1.0       2.0
                 2024-03-25  0.013380    1.346989  1.0       2.0
                 2024-03-26  0.008325    0.835940  0.0       1.0
                 2024-03-27  0.007452    0.747946  0.0       1.0
                 2024-03-28  0.005610    0.562598  0.0       1.0
                 2024-03-29 -0.001304   -0.130306  3.0       1.0
                 2024-03-30 -0.007805   -0.777451  3.0       1.0
                 2024-03-31 -0.007669   -0.763955  3.0       1.0
                 2024-04-01  0.002758    0.276187  3.0       1.0
                 2024-04-02  0.008642    0.867910  3.0       0.0
                 2024-04-03  0.012379    1.245551  4.0       0.0
                 2024-04-04  0.016243    1.637556  4.0       0.0
                 2024-04-05  0.015608    1.573014  1.0       3.0
                 2024-04-06  0.026398    2.674961  1.0       3.0
                 2024-04-07  0.023116    2.338503  1.0       3.0
                 2024-04-08  0.011681    1.174989  1.0       3.0
                 2024-04-09  0.008367    0.840259  1.0       3.0
                 2024-04-10  0.004183    0.419152  0.0       4.0
                 2024-04-11 -0.000311   -0.031086  0.0       4.0
                 2024-04-12 -0.002093   -0.209069  1.0       1.0
                 2024-04-13 -0.008671   -0.863305  1.0       1.0
                 2024-04-14 -0.008002   -0.797030  1.0       1.0
                 2024-04-15 -0.000752   -0.075185  1.0       1.0

                             Prevalence_7  Prevalence_7_percentage  \
location lineage date
USA      BA.2.86 2024-02-29      0.004063                 0.406311
                 2024-03-01      0.004145                 0.414474
                 2024-03-02      0.004149                 0.414907
                 2024-03-03      0.004278                 0.427836
                 2024-03-04      0.004393                 0.439257
                 2024-03-05      0.004736                 0.473620
                 2024-03-06      0.004802                 0.480241
                 2024-03-07      0.004818                 0.481785
                 2024-03-08      0.004792                 0.479154
                 2024-03-09      0.004768                 0.476801
                 2024-03-10      0.004747                 0.474681
                 2024-03-11      0.004915                 0.491475
Global   BA.2.86 2024-02-29      0.001970                 0.197001
                 2024-03-01      0.001984                 0.198432
                 2024-03-02      0.001903                 0.190299
                 2024-03-03      0.001818                 0.181829
                 2024-03-04      0.001817                 0.181663
                 2024-03-05      0.001910                 0.191015
                 2024-03-06      0.001761                 0.176072
                 2024-03-07      0.001779                 0.177879
                 2024-03-08      0.001796                 0.179581
                 2024-03-09      0.001838                 0.183787
                 2024-03-10      0.001840                 0.184010
                 2024-03-11      0.001896                 0.189634
                 2024-03-12      0.001935                 0.193499
                 2024-03-13      0.001928                 0.192788
                 2024-03-14      0.001921                 0.192072
                 2024-03-15      0.002048                 0.204798
                 2024-03-16      0.002056                 0.205608
                 2024-03-17      0.002003                 0.200309
                 2024-03-18      0.002044                 0.204417
                 2024-03-19      0.002069                 0.206945
                 2024-03-20      0.002077                 0.207668
                 2024-03-21      0.002099                 0.209920
                 2024-03-22      0.002161                 0.216063
                 2024-03-23      0.002199                 0.219912
                 2024-03-24      0.002239                 0.223876
                 2024-03-25      0.002244                 0.224443
                 2024-03-26      0.002193                 0.219335
                 2024-03-27      0.002188                 0.218763
                 2024-03-28      0.002183                 0.218310
                 2024-03-29      0.002141                 0.214104
                 2024-03-30      0.002082                 0.208244
                 2024-03-31      0.002122                 0.212200
                 2024-04-01      0.002288                 0.228808
                 2024-04-02      0.002330                 0.232981
                 2024-04-03      0.002385                 0.238517
                 2024-04-04      0.002445                 0.244534
                 2024-04-05      0.002388                 0.238762
                 2024-04-06      0.002504                 0.250404
                 2024-04-07      0.002494                 0.249377
                 2024-04-08      0.002483                 0.248255
                 2024-04-09      0.002470                 0.247000
                 2024-04-10      0.002456                 0.245587
                 2024-04-11      0.002440                 0.244003
                 2024-04-12      0.002353                 0.235298
                 2024-04-13      0.002357                 0.235693
                 2024-04-14      0.002358                 0.235824
                 2024-04-15      0.002470                 0.246955

                             confidenceInterval20  confidenceInterval35  \
location lineage date
USA      BA.2.86 2024-02-29              1.245111              2.241199
                 2024-03-01              1.255750              2.260349
                 2024-03-02              1.272414              2.290346
                 2024-03-03              1.281266              2.306278
                 2024-03-04              1.288176              2.318717
                 2024-03-05              1.271519              2.288734
                 2024-03-06              1.275438              2.295789
                 2024-03-07              1.280715              2.305286
                 2024-03-08              1.275266              2.295478
                 2024-03-09              1.281132              2.306037
                 2024-03-10              1.267254              2.281057
                 2024-03-11              1.239374              2.230873
Global   BA.2.86 2024-02-29              0.728315              1.310967
                 2024-03-01              0.735368              1.323663
                 2024-03-02              0.749589              1.349260
                 2024-03-03              0.733742              1.320736
                 2024-03-04              0.738155              1.328679
                 2024-03-05              0.739110              1.330398
                 2024-03-06              0.783519              1.410335
                 2024-03-07              0.795968              1.432742
                 2024-03-08              0.808820              1.455876
                 2024-03-09              0.821284              1.478311
                 2024-03-10              0.835956              1.504720
                 2024-03-11              0.835872              1.504570
                 2024-03-12              0.823431              1.482175
                 2024-03-13              0.877406              1.579331
                 2024-03-14              0.890767              1.603381
                 2024-03-15              0.884378              1.591880
                 2024-03-16              0.886379              1.595483
                 2024-03-17              0.903140              1.625651
                 2024-03-18              0.904963              1.628934
                 2024-03-19              0.914236              1.645624
                 2024-03-20              0.930410              1.674737
                 2024-03-21              0.939878              1.691781
                 2024-03-22              0.910084              1.638151
                 2024-03-23              0.919026              1.654247
                 2024-03-24              0.943118              1.697613
                 2024-03-25              0.960566              1.729019
                 2024-03-26              0.983105              1.769590
                 2024-03-27              0.992563              1.786614
                 2024-03-28              0.993309              1.787955
                 2024-03-29              0.989766              1.781578
                 2024-03-30              0.993801              1.788843
                 2024-03-31              0.994754              1.790557
                 2024-04-01              0.986429              1.775573
                 2024-04-02              1.017916              1.832248
                 2024-04-03              1.021782              1.839208
                 2024-04-04              1.025797              1.846434
                 2024-04-05              1.058530              1.905354
                 2024-04-06              1.065037              1.917066
                 2024-04-07              1.061272              1.910290
                 2024-04-08              1.023419              1.842154
                 2024-04-09              1.030313              1.854563
                 2024-04-10              1.027600              1.849680
                 2024-04-11              1.025544              1.845979
                 2024-04-12              1.065548              1.917986
                 2024-04-13              1.049951              1.889912
                 2024-04-14              1.056009              1.900815
                 2024-04-15              1.046741              1.884133

                             confidenceInterval5  confidenceInterval50  ...  \
location lineage date                                                   ...
USA      BA.2.86 2024-02-29             0.298827              3.336897  ...
                 2024-03-01             0.301380              3.365409  ...
                 2024-03-02             0.305379              3.410071  ...
                 2024-03-03             0.307504              3.433792  ...
                 2024-03-04             0.309162              3.452313  ...
                 2024-03-05             0.305165              3.407671  ...
                 2024-03-06             0.306105              3.418175  ...
                 2024-03-07             0.307371              3.432315  ...
                 2024-03-08             0.306064              3.417712  ...
                 2024-03-09             0.307472              3.433433  ...
                 2024-03-10             0.304141              3.396241  ...
                 2024-03-11             0.297450              3.321522  ...
Global   BA.2.86 2024-02-29             0.174796              1.951884  ...
                 2024-03-01             0.176488              1.970788  ...
                 2024-03-02             0.179901              2.008898  ...
                 2024-03-03             0.176098              1.966429  ...
                 2024-03-04             0.177157              1.978256  ...
                 2024-03-05             0.177386              1.980815  ...
                 2024-03-06             0.188045              2.099832  ...
                 2024-03-07             0.191032              2.133194  ...
                 2024-03-08             0.194117              2.167637  ...
                 2024-03-09             0.197108              2.201041  ...
                 2024-03-10             0.200629              2.240361  ...
                 2024-03-11             0.200609              2.240137  ...
                 2024-03-12             0.197623              2.206795  ...
                 2024-03-13             0.210578              2.351449  ...
                 2024-03-14             0.213784              2.387257  ...
                 2024-03-15             0.212251              2.370133  ...
                 2024-03-16             0.212731              2.375497  ...
                 2024-03-17             0.216754              2.420414  ...
                 2024-03-18             0.217191              2.425302  ...
                 2024-03-19             0.219417              2.450152  ...
                 2024-03-20             0.223298              2.493498  ...
                 2024-03-21             0.225571              2.518874  ...
                 2024-03-22             0.218420              2.439025  ...
                 2024-03-23             0.220566              2.462991  ...
                 2024-03-24             0.226348              2.527558  ...
                 2024-03-25             0.230536              2.574317  ...
                 2024-03-26             0.235945              2.634723  ...
                 2024-03-27             0.238215              2.660070  ...
                 2024-03-28             0.238394              2.662067  ...
                 2024-03-29             0.237544              2.652572  ...
                 2024-03-30             0.238512              2.663388  ...
                 2024-03-31             0.238741              2.665940  ...
                 2024-04-01             0.236743              2.643631  ...
                 2024-04-02             0.244300              2.728014  ...
                 2024-04-03             0.245228              2.738376  ...
                 2024-04-04             0.246191              2.749135  ...
                 2024-04-05             0.254047              2.836860  ...
                 2024-04-06             0.255609              2.854299  ...
                 2024-04-07             0.254705              2.844209  ...
                 2024-04-08             0.245621              2.742763  ...
                 2024-04-09             0.247275              2.761239  ...
                 2024-04-10             0.246624              2.753968  ...
                 2024-04-11             0.246130              2.748457  ...
                 2024-04-12             0.255731              2.855668  ...
                 2024-04-13             0.251988              2.813869  ...
                 2024-04-14             0.253442              2.830103  ...
                 2024-04-15             0.251218              2.805265  ...

                             confidenceInterval80  confidenceInterval95  \
location lineage date
USA      BA.2.86 2024-02-29              6.374967              9.761668
                 2024-03-01              6.429438              9.845077
                 2024-03-02              6.514762              9.975729
                 2024-03-03              6.560081             10.045124
                 2024-03-04              6.595463             10.099303
                 2024-03-05              6.510177              9.968709
                 2024-03-06              6.530245              9.999438
                 2024-03-07              6.557258             10.040802
                 2024-03-08              6.529361              9.998083
                 2024-03-09              6.559395             10.044073
                 2024-03-10              6.488341              9.935272
                 2024-03-11              6.345595              9.716692
Global   BA.2.86 2024-02-29              3.728972              5.709989
                 2024-03-01              3.765087              5.765289
                 2024-03-02              3.837896              5.876778
                 2024-03-03              3.756760              5.752539
                 2024-03-04              3.779354              5.787136
                 2024-03-05              3.784243              5.794623
                 2024-03-06              4.011620              6.142793
                 2024-03-07              4.075356              6.240389
                 2024-03-08              4.141158              6.341148
                 2024-03-09              4.204974              6.438867
                 2024-03-10              4.280092              6.553891
                 2024-03-11              4.279664              6.553236
                 2024-03-12              4.215966              6.455698
                 2024-03-13              4.492320              6.878865
                 2024-03-14              4.560729              6.983617
                 2024-03-15              4.528015              6.933523
                 2024-03-16              4.538263              6.949215
                 2024-03-17              4.624075              7.080615
                 2024-03-18              4.633413              7.094913
                 2024-03-19              4.680887              7.167609
                 2024-03-20              4.763697              7.294411
                 2024-03-21              4.812177              7.368646
                 2024-03-22              4.659631              7.135060
                 2024-03-23              4.705415              7.205166
                 2024-03-24              4.828767              7.394049
                 2024-03-25              4.918098              7.530837
                 2024-03-26              5.033500              7.707547
                 2024-03-27              5.081924              7.781696

In [21]:
outbreak_data.get_wastewater_latest(region="Ohio", server='dev.outbreak.info')

GET https://dev.outbreak.info/wastewater_metadata/query?size=1&sort=-collection_date&fields=collection_date&q=geo_loc_region:Ohio AND demix_success:true AND variants_success:true

'2024-06-26'

In [22]:
outbreak_data.gr_significance(['USA', 'Global'])

GET https://api.outbreak.info/significance/query?q=loc:(USA OR Global) AND growing:true&sort=-sig&size=5

,_id,_score,growing,leaf,loc,sig,snr
lin,,,,,,,
B.1.1.529.2.86.1.1.11.1.3+,Global_B.1.1.529.2.86.1.1.11.1.3+,None,true,false,Global,108.7890952414096,10.259105275045819
KP+,Global_KP+,None,true,false,Global,108.7890952414096,10.259105275045819
B.1.1.529.2.86.1.1.7+,Global_B.1.1.529.2.86.1.1.7+,None,true,false,Global,98.55161318526439,9.749491667932192
JN.1.7+,Global_JN.1.7+,None,true,false,Global,95.3253214678445,9.583326603086226
JN.1.7,Global_JN.1.7,None,true,true,Global,95.3231147227556,9.583211971415446

In [23]:
#Retrieve sample data from 2023-06-01 to the last date for wastewater data collection in Ohio.
last_ww_date = outbreak_data.get_wastewater_latest(region="Ohio", server='dev.outbreak.info')
d = outbreak_data.get_wastewater_samples(collection_site_id="USA_OH_5f9e5487", viral_load_at_least=25000, date_range=["2023-09-01", last_ww_date], server='dev.outbreak.info')
print(d)

GET https://dev.outbreak.info/wastewater_metadata/query?size=1&sort=-collection_date&fields=collection_date&q=geo_loc_region:Ohio AND demix_success:true AND variants_success:true
GET https://dev.outbreak.info/wastewater_metadata/query?q=collection_site_id:USA_OH_5f9e5487 AND collection_date:[2023-09-01 TO 2024-06-26] AND viral_load:>=25000 AND demix_success:true AND variants_success:true&fetch_all=true
GET https://dev.outbreak.info/wastewater_metadata/query?scroll_id=FGluY2x1ZGVfY29udGV4dF91dWlkDXF1ZXJ5QW5kRmV0Y2gBFnNKbEd4cUZSVEEtOXdfRy1JVV8tMmcAAAAAACDy2BZHV0dfbkk2elNUS2dCdTI1dzA4T3F3&fetch_all=true&page=0&fetch_all=true
                collection_site_id  \
collection_date
2023-09-06         USA_OH_5f9e5487
2023-09-25         USA_OH_5f9e5487
2023-09-18         USA_OH_5f9e5487
2023-10-16         USA_OH_5f9e5487
2023-10-30         USA_OH_5f9e5487
2023-10-23         USA_OH_5f9e5487
2023-11-27         USA_OH_5f9e5487
2023-11-20         USA_OH_5f9e5487
2023-11-13         USA_OH_5f9e5487
2023-11-06         USA_OH_5f9e5487

                                                coverage_intervals  \
collection_date
2023-09-06       [{'end': 2243, 'start': 34}, {'end': 2877, 'st...
2023-09-25       [{'end': 1333, 'start': 970}, {'end': 1921, 's...
2023-09-18       [{'end': 1013, 'start': 670}, {'end': 1921, 's...
2023-10-16       [{'end': 1921, 'start': 1566}, {'end': 2265, '...
2023-10-30       [{'end': 701, 'start': 348}, {'end': 1333, 'st...
2023-10-23       [{'end': 1333, 'start': 970}, {'end': 3765, 's...
2023-11-27       [{'end': 3152, 'start': 348}, {'end': 6243, 's...
2023-11-20       [{'end': 5298, 'start': 4652}, {'end': 5928, '...
2023-11-13       [{'end': 701, 'start': 348}, {'end': 4383, 'st...
2023-11-06       [{'end': 1917, 'start': 348}, {'end': 1921, 's...

                 demix_success geo_loc_country geo_loc_region sra_accession  \
collection_date
2023-09-06                True             USA           Ohio   SRR26133858
2023-09-25                True             USA           Ohio   SRR26549478
2023-09-18                True             USA           Ohio   SRR26549479
2023-10-16                True             USA           Ohio   SRR26666642
2023-10-30                True             USA           Ohio   SRR26769118
2023-10-23                True             USA           Ohio   SRR26769119
2023-11-27                True             USA           Ohio   SRR27209427
2023-11-20                True             USA           Ohio   SRR27209428
2023-11-13                True             USA           Ohio   SRR27209429
2023-11-06                True             USA           Ohio   SRR27209430

                 variants_success  viral_load  ww_population  \
collection_date
2023-09-06                   True     98147.5         226729
2023-09-25                   True     51116.0         226729
2023-09-18                   True     40253.0         226729
2023-10-16                   True     44631.5         226729
2023-10-30                   True    105726.5         226729
2023-10-23                   True    104084.5         226729
2023-11-27                   True     90400.0         226729
2023-11-20                   True    100547.5         226729
2023-11-13                   True     68842.0         226729
2023-11-06                   True     43915.5         226729

                 normed_viral_load
collection_date
2023-09-06                3.539715
2023-09-25                1.843512
2023-09-18                1.451735
2023-10-16                1.609647
2023-10-30                3.813054
2023-10-23                3.753835
2023-11-27                3.260300
2023-11-20                3.626272
2023-11-13                2.482805
2023-11-06                1.583824

In [24]:
print(outbreak_data.get_wastewater_samples(collection_site_id="USA_OH_5f9e5487", viral_load_at_least=25000, server='dev.outbreak.info'))

GET https://dev.outbreak.info/wastewater_metadata/query?q=collection_site_id:USA_OH_5f9e5487 AND viral_load:>=25000 AND demix_success:true AND variants_success:true&fetch_all=true
GET https://dev.outbreak.info/wastewater_metadata/query?scroll_id=FGluY2x1ZGVfY29udGV4dF91dWlkDXF1ZXJ5QW5kRmV0Y2gBFnNKbEd4cUZSVEEtOXdfRy1JVV8tMmcAAAAAACDy2RZHV0dfbkk2elNUS2dCdTI1dzA4T3F3&fetch_all=true&page=0&fetch_all=true
                collection_site_id  \
collection_date
2022-06-27         USA_OH_5f9e5487
2022-07-20         USA_OH_5f9e5487
2023-03-13         USA_OH_5f9e5487
2023-04-17         USA_OH_5f9e5487
2023-03-06         USA_OH_5f9e5487
2023-08-07         USA_OH_5f9e5487
2022-12-28         USA_OH_5f9e5487
2022-12-26         USA_OH_5f9e5487
2022-12-12         USA_OH_5f9e5487
2022-12-05         USA_OH_5f9e5487
2023-02-06         USA_OH_5f9e5487
2022-11-07         USA_OH_5f9e5487
2023-01-23         USA_OH_5f9e5487
2023-01-04         USA_OH_5f9e5487
2023-04-24         USA_OH_5f9e5487
2023-02-13         USA_OH_5f9e5487
2023-02-27         USA_OH_5f9e5487
2023-02-22         USA_OH_5f9e5487
2023-03-20         USA_OH_5f9e5487
2023-05-08         USA_OH_5f9e5487
2023-08-21         USA_OH_5f9e5487
2022-10-31         USA_OH_5f9e5487
2022-10-24         USA_OH_5f9e5487
2022-10-17         USA_OH_5f9e5487
2022-10-10         USA_OH_5f9e5487
2022-10-03         USA_OH_5f9e5487
2023-05-22         USA_OH_5f9e5487
2023-06-12         USA_OH_5f9e5487
2023-03-27         USA_OH_5f9e5487
2023-09-06         USA_OH_5f9e5487
2023-09-25         USA_OH_5f9e5487
2023-09-18         USA_OH_5f9e5487
2022-12-19         USA_OH_5f9e5487
2022-11-28         USA_OH_5f9e5487
2022-11-21         USA_OH_5f9e5487
2022-11-14         USA_OH_5f9e5487
2023-08-28         USA_OH_5f9e5487
2023-10-16         USA_OH_5f9e5487
2023-10-30         USA_OH_5f9e5487
2023-10-23         USA_OH_5f9e5487
2023-11-27         USA_OH_5f9e5487
2023-11-20         USA_OH_5f9e5487
2023-11-13         USA_OH_5f9e5487
2023-11-06         USA_OH_5f9e5487

                                                coverage_intervals  \
collection_date
2022-06-27       [{'end': 4383, 'start': 54}, {'end': 15332, 's...
2022-07-20       [{'end': 2237, 'start': 348}, {'end': 2270, 's...
2023-03-13       [{'end': 404, 'start': 54}, {'end': 2224, 'sta...
2023-04-17       [{'end': 404, 'start': 54}, {'end': 1013, 'sta...
2023-03-06       [{'end': 1619, 'start': 1270}, {'end': 2224, '...
2023-08-07       [{'end': 4991, 'start': 4652}, {'end': 17078, ...
2022-12-28       [{'end': 4383, 'start': 348}, {'end': 6549, 's...
2022-12-26       [{'end': 701, 'start': 348}, {'end': 4383, 'st...
2022-12-12       [{'end': 80, 'start': 74}, {'end': 1013, 'star...
2022-12-05       [{'end': 1619, 'start': 348}, {'end': 2202, 's...
2023-02-06       [{'end': 701, 'start': 348}, {'end': 1333, 'st...
2022-11-07       [{'end': 1333, 'start': 54}, {'end': 2224, 'st...
2023-01-23       [{'end': 1013, 'start': 670}, {'end': 5616, 's...
2023-01-04       [{'end': 701, 'start': 348}, {'end': 1333, 'st...
2023-04-24       [{'end': 701, 'start': 348}, {'end': 1333, 'st...
2023-02-13       [{'end': 2857, 'start': 348}, {'end': 3466, 's...
2023-02-27       [{'end': 4383, 'start': 348}, {'end': 5298, 's...
2023-02-22       [{'end': 4383, 'start': 348}, {'end': 4991, 's...
2023-03-20       [{'end': 1333, 'start': 348}, {'end': 1921, 's...
2023-05-08       [{'end': 1013, 'start': 670}, {'end': 1619, 's...
2023-08-21       [{'end': 377, 'start': 54}, {'end': 381, 'star...
2022-10-31       [{'end': 2224, 'start': 1879}, {'end': 2857, '...
2022-10-24       [{'end': 3466, 'start': 3106}, {'end': 5298, '...
2022-10-17       [{'end': 701, 'start': 348}, {'end': 1921, 'st...
2022-10-10       [{'end': 1333, 'start': 970}, {'end': 1429, 's...
2022-10-03       [{'end': 701, 'start': 348}, {'end': 1333, 'st...
2023-05-22       [{'end': 12891, 'start': 12550}, {'end': 19873...
2023-06-12       [{'end': 1333, 'start': 970}, {'end': 1921, 's...
2023-03-27       [{'end': 1013, 'start': 670}, {'end': 1619, 's...
2023-09-06       [{'end': 2243, 'start': 34}, {'end': 2877, 'st...
2023-09-25       [{'end': 1333, 'start': 970}, {'end': 1921, 's...
2023-09-18       [{'end': 1013, 'start': 670}, {'end': 1921, 's...
2022-12-19       [{'end': 4383, 'start': 54}, {'end': 4630, 'st...
2022-11-28       [{'end': 4383, 'start': 54}, {'end': 5928, 'st...
2022-11-21       [{'end': 140, 'start': 138}, {'end': 142, 'sta...
2022-11-14       [{'end': 2224, 'start': 54}, {'end': 4383, 'st...
2023-08-28       [{'end': 1333, 'start': 670}, {'end': 3466, 's...
2023-10-16       [{'end': 1921, 'start': 1566}, {'end': 2265, '...
2023-10-30       [{'end': 701, 'start': 348}, {'end': 1333, 'st...
2023-10-23       [{'end': 1333, 'start': 970}, {'end': 3765, 's...
2023-11-27       [{'end': 3152, 'start': 348}, {'end': 6243, 's...
2023-11-20       [{'end': 5298, 'start': 4652}, {'end': 5928, '...
2023-11-13       [{'end': 701, 'start': 348}, {'end': 4383, 'st...
2023-11-06       [{'end': 1917, 'start': 348}, {'end': 1921, 's...

                 demix_success geo_loc_country geo_loc_region sra_accession  \
collection_date
2022-06-27                True             USA           Ohio   SRR24040790
2022-07-20                True             USA           Ohio   SRR24054406
2023-03-13                True             USA           Ohio   SRR24063051
2023-04-17                True             USA           Ohio   SRR24335713
2023-03-06                True             USA           Ohio   SRR24063052
2023-08-07                True             USA           Ohio   SRR25757732
2022-12-28                True             USA           Ohio   SRR24057376
2022-12-26                True             USA           Ohio   SRR24057377
2022-12-12                True             USA           Ohio   SRR24057379
2022-12-05                True             USA           Ohio   SRR24057380
2023-02-06                True             USA           Ohio   SRR24057386
2022-11-07                True             USA           Ohio   SRR24057384
2023-01-23                True             USA           Ohio   SRR24057387
2023-01-04                True             USA           Ohio   SRR24057389
2023-04-24                True             USA           Ohio   SRR24529558
2023-02-13                True             USA           Ohio   SRR24057385
2023-02-27                True             USA           Ohio   SRR24063053
2023-02-22                True             USA           Ohio   SRR24063054
2023-03-20                True             USA           Ohio   SRR24093827
2023-05-08                True             USA           Ohio   SRR24900753
2023-08-21                True             USA           Ohio   SRR25833262
2022-10-31                True             USA           Ohio   SRR24054714
2022-10-24                True             USA           Ohio   SRR24054715
2022-10-17                True             USA           Ohio   SRR24054716
2022-10-10                True             USA           Ohio   SRR24054717
2022-10-03                True             USA           Ohio   SRR24054718
2023-05-22                True             USA           Ohio   SRR24900752
2023-06-12                True             USA           Ohio   SRR25109057
2023-03-27                True             USA           Ohio   SRR24148627
2023-09-06                True             USA           Ohio   SRR26133858
2023-09-25                True             USA           Ohio   SRR26549478
2023-09-18                True             USA           Ohio   SRR26549479
2022-12-19                True             USA           Ohio   SRR24057378
2022-11-28                True             USA           Ohio   SRR24057381
2022-11-21                True             USA           Ohio   SRR24057382
2022-11-14                True             USA           Ohio   SRR24057383
2023-08-28                True             USA           Ohio   SRR25939637
2023-10-16                True             USA           Ohio   SRR26666642
2023-10-30                True             USA           Ohio   SRR26769118
2023-10-23                True             USA           Ohio   SRR26769119
2023-11-27                True             USA           Ohio   SRR27209427
2023-11-20                True             USA           Ohio   SRR27209428
2023-11-13                True             USA           Ohio   SRR27209429
2023-11-06                True             USA           Ohio   SRR27209430

                 variants_success    viral_load  ww_population  \
collection_date
2022-06-27                   True   27651.00000         226729
2022-07-20                   True   34773.50000         226729
2023-03-13                   True   57432.00000         226729
2023-04-17                   True   27326.00000         226729
2023-03-06                   True   25600.00000         226729
2023-08-07                   True   27873.50000         226729
2022-12-28                   True  248631.50000         226729
2022-12-26                   True  318610.50000         226729
2022-12-12                   True  128126.50000         226729
2022-12-05                   True  194274.00000         226729
2023-02-06                   True   76968.50000         226729
2022-11-07                   True   84505.50000         226729
2023-01-23                   True   68674.00000         226729
2023-01-04                   True  176210.50000         226729
2023-04-24                   True   26778.94737         226729
2023-02-13                   True   75915.50000         226729
2023-02-27                   True   84000.00000         226729
2023-02-22                   True   67874.00000         226729
2023-03-20                   True   39242.00000         226729
2023-05-08                   True   26947.50000         226729
2023-08-21                   True   29810.50000         226729
2022-10-31                   True   61979.00000         226729
2022-10-24                   True   61853.00000         226729
2022-10-17                   True   80211.00000         226729
2022-10-10                   True   67284.00000         226729
2022-10-03                   True   36421.00000         226729
2023-05-22                   True   27326.50000         226729
2023-06-12                   True   25684.00000         226729
2023-03-27                   True   29221.00000         226729
2023-09-06                   True   98147.50000         226729
2023-09-25                   True   51116.00000         226729
2023-09-18                   True   40253.00000         226729
2022-12-19                   True  174063.00000         226729
2022-11-28                   True  197052.50000         226729
2022-11-21                   True  302526.50000         226729
2022-11-14                   True   76210.50000         226729
2023-08-28                   True   26947.50000         226729
2023-10-16                   True   44631.50000         226729
2023-10-30                   True  105726.50000         226729
2023-10-23                   True  104084.50000         226729
2023-11-27                   True   90400.00000         226729
2023-11-20                   True  100547.50000         226729
2023-11-13                   True   68842.00000         226729
2023-11-06                   True   43915.50000         226729

                 normed_viral_load
collection_date
2022-06-27                0.381668
2022-07-20                0.479980
2023-03-13                0.792735
2023-04-17                0.377182
2023-03-06                0.353357
2023-08-07                0.384739
2022-12-28                3.431867
2022-12-26                4.397789
2022-12-12                1.768534
2022-12-05                2.681569
2023-02-06                1.062398
2022-11-07                1.166432
2023-01-23                0.947909
2023-01-04                2.432238
2023-04-24                0.369631
2023-02-13                1.047864
2023-02-27                1.159454
2023-02-22                0.936867
2023-03-20                0.541658
2023-05-08                0.371957
2023-08-21                0.411475
2022-10-31                0.855498
2022-10-24                0.853759
2022-10-17                1.107155
2022-10-10                0.928723
2022-10-03                0.502720
2023-05-22                0.377188
2023-06-12                0.354517
2023-03-27                0.403338
2023-09-06                1.354733
2023-09-25                0.705556
2023-09-18                0.555613
2022-12-19                2.402596
2022-11-28                2.719921
2022-11-21                4.175782
2022-11-14                1.051936
2023-08-28                0.371957
2023-10-16                0.616050
2023-10-30                1.459346
2023-10-23                1.436681
2023-11-27                1.247794
2023-11-20                1.387860
2023-11-13                0.950228
2023-11-06                0.606167

In [25]:
s = outbreak_data.get_wastewater_samples_by_lineage('EG.5.1', server='dev.outbreak.info') #Dud endpoints?
s = outbreak_data.get_wastewater_metadata(s, server='dev.outbreak.info')
outbreak_data.get_wastewater_mutations(s, server='dev.outbreak.info')

GET https://dev.outbreak.info/wastewater_demix/query?q=prevalence:>=0.01 AND name:EG.5.1&fetch_all=true
GET https://dev.outbreak.info/wastewater_demix/query?scroll_id=FGluY2x1ZGVfY29udGV4dF91dWlkDXF1ZXJ5QW5kRmV0Y2gBFnNKbEd4cUZSVEEtOXdfRy1JVV8tMmcAAAAAACDy2hZHV0dfbkk2elNUS2dCdTI1dzA4T3F3&fetch_all=true&page=0&fetch_all=true
GET https://dev.outbreak.info/wastewater_demix/query?scroll_id=FGluY2x1ZGVfY29udGV4dF91dWlkDXF1ZXJ5QW5kRmV0Y2gBFnNKbEd4cUZSVEEtOXdfRy1JVV8tMmcAAAAAACDy2hZHV0dfbkk2elNUS2dCdTI1dzA4T3F3&fetch_all=true&page=1&fetch_all=true
GET https://dev.outbreak.info/wastewater_demix/query?scroll_id=FGluY2x1ZGVfY29udGV4dF91dWlkDXF1ZXJ5QW5kRmV0Y2gBFnNKbEd4cUZSVEEtOXdfRy1JVV8tMmcAAAAAACDy2hZHV0dfbkk2elNUS2dCdTI1dzA4T3F3&fetch_all=true&page=2&fetch_all=true
POST https://dev.outbreak.info/wastewater_metadata/query/?size=1000
POST https://dev.outbreak.info/wastewater_variants/query/?size=1000

                                 coverage  \
collection_date        mutation
2023-06-26      EG.5.1 13195A    33.65883
                       13198T    33.65883
                       13211T    33.65883
                       13212A    33.65883
                       13221T    33.65883
...                                   ...
2024-01-09      EG.5.1 17084N    98.49179
                       17086G    98.49179
                       17087G    98.49179
                       17089N    98.49179
                       17102N    98.49179

                                                                            crumbs  \
collection_date        mutation
2023-06-26      EG.5.1 13195A    ;XBB;XBB.1;XBB.1.9;XBB.1.9.2;XBB.1.9.2.5;XBB.1...
                       13198T    ;XBB;XBB.1;XBB.1.9;XBB.1.9.2;XBB.1.9.2.5;XBB.1...
                       13211T    ;XBB;XBB.1;XBB.1.9;XBB.1.9.2;XBB.1.9.2.5;XBB.1...
                       13212A    ;XBB;XBB.1;XBB.1.9;XBB.1.9.2;XBB.1.9.2.5;XBB.1...
                       13221T    ;XBB;XBB.1;XBB.1.9;XBB.1.9.2;XBB.1.9.2.5;XBB.1...
...                                                                            ...
2024-01-09      EG.5.1 17084N    ;XBB;XBB.1;XBB.1.9;XBB.1.9.2;XBB.1.9.2.5;XBB.1...
                       17086G    ;XBB;XBB.1;XBB.1.9;XBB.1.9.2;XBB.1.9.2.5;XBB.1...
                       17087G    ;XBB;XBB.1;XBB.1.9;XBB.1.9.2;XBB.1.9.2.5;XBB.1...
                       17089N    ;XBB;XBB.1;XBB.1.9;XBB.1.9.2;XBB.1.9.2.5;XBB.1...
                       17102N    ;XBB;XBB.1;XBB.1.9;XBB.1.9.2;XBB.1.9.2.5;XBB.1...

                                   name  prevalence_x  spike_coverage  \
collection_date        mutation
2023-06-26      EG.5.1 13195A    EG.5.1      0.331873       62.506541
                       13198T    EG.5.1      0.331873       62.506541
                       13211T    EG.5.1      0.331873       62.506541
                       13212A    EG.5.1      0.331873       62.506541
                       13221T    EG.5.1      0.331873       62.506541
...                                 ...           ...             ...
2024-01-09      EG.5.1 17084N    EG.5.1      0.059489        0.000000
                       17086G    EG.5.1      0.059489        0.000000
                       17087G    EG.5.1      0.059489        0.000000
                       17089N    EG.5.1      0.059489        0.000000
                       17102N    EG.5.1      0.059489        0.000000

                                sra_accession      query_x collection_site_id  \
collection_date        mutation
2023-06-26      EG.5.1 13195A     SRR25548525  SRR25548525    USA_OH_71d9a9a5
                       13198T     SRR25548525  SRR25548525    USA_OH_71d9a9a5
                       13211T     SRR25548525  SRR25548525    USA_OH_71d9a9a5
                       13212A     SRR25548525  SRR25548525    USA_OH_71d9a9a5
                       13221T     SRR25548525  SRR25548525    USA_OH_71d9a9a5
...                                       ...          ...                ...
2024-01-09      EG.5.1 17084N     SRR27563999  SRR27563999    USA_ME_90ee1766
                       17086G     SRR27563999  SRR27563999    USA_ME_90ee1766
                       17087G     SRR27563999  SRR27563999    USA_ME_90ee1766
                       17089N     SRR27563999  SRR27563999    USA_ME_90ee1766
                       17102N     SRR27563999  SRR27563999    USA_ME_90ee1766

                                                                coverage_intervals  \
collection_date        mutation
2023-06-26      EG.5.1 13195A    [{'end': 12891, 'start': 12259}, {'end': 13502...
                       13198T    [{'end': 12891, 'start': 12259}, {'end': 13502...
                       13211T    [{'end': 12891, 'start': 12259}, {'end': 13502...
                       13212A    [{'end': 12891, 'start': 12259}, {'end': 13502...
                       13221T    [{'end': 12891, 'start': 12259}, {'end': 13502...
...                                                                            ...
2024-01-09      EG.5.1 17084N    [{'end': 2255, 'start': 82}, {'end': 5394, 'st...
                       17086G    [{'end': 2255, 'start': 82}, {'end': 5394, 'st...
                       17087G    [{'end': 2255, 'start': 82}, {'end': 5394, 'st...
                       17089N    [{'end': 2255, 'start': 82}, {'end': 5394, 'st...
                       17102N    [{'end': 2255, 'start': 82}, {'end': 5394, 'st...

                                demix_success  ... variants_success  \
collection_date        mutation                ...
2023-06-26      EG.5.1 13195A            True  ...             True
                       13198T            True  ...             True
                       13211T            True  ...             True
                       13212A            True  ...             True
                       13221T            True  ...             True
...                                       ...  ...              ...
2024-01-09      EG.5.1 17084N            True  ...             True
                       17086G            True  ...             True
                       17087G            True  ...             True
                       17089N            True  ...             True
                       17102N            True  ...             True

                                viral_load ww_population  normed_viral_load  \
collection_date        mutation
2023-06-26      EG.5.1 13195A       6500.0       36000.0                NaN
                       13198T       6500.0       36000.0                NaN
                       13211T       6500.0       36000.0                NaN
                       13212A       6500.0       36000.0                NaN
                       13221T       6500.0       36000.0                NaN
...                                    ...           ...                ...
2024-01-09      EG.5.1 17084N          NaN        3000.0                NaN
                       17086G          NaN        3000.0                NaN
                       17087G          NaN        3000.0                NaN
                       17089N          NaN        3000.0                NaN
                       17102N          NaN        3000.0                NaN

                                     query_y  alt_base  depth prevalence_y  \
collection_date        mutation
2023-06-26      EG.5.1 13195A    SRR25548525         A   32.0     0.002320
                       13198T    SRR25548525         T   45.0     0.003253
                       13211T    SRR25548525         T   20.0     0.001361
                       13212A    SRR25548525         A   21.0     0.001428
                       13221T    SRR25548525         T   34.0     0.002277
...                                      ...       ...    ...          ...
2024-01-09      EG.5.1 17084N    SRR27563999         N   69.0     0.004413
                       17086G    SRR27563999         G   37.0     0.002366
                       17087G    SRR27563999         G  164.0     0.010489
                       17089N    SRR27563999         N  237.0     0.015162
                       17102N    SRR27563999         N   36.0     0.002303

                                 ref_base     site
collection_date        mutation
2023-06-26      EG.5.1 13195A           T  13195.0
                       13198T           A  13198.0
                       13211T           A  13211.0
                       13212A           T  13212.0
                       13221T           A  13221.0
...                                   ...      ...
2024-01-09      EG.5.1 17084N           C  17084.0
                       17086G           C  17086.0
                       17087G           C  17087.0
                       17089N           G  17089.0
                       17102N           G  17102.0

[952004 rows x 22 columns]

In [28]:
samples = outbreak_data.get_wastewater_samples_by_mutation(site=1003, alt_base='G', server='dev.outbreak.info')
samples

GET https://dev.outbreak.info/wastewater_variants/query?q=prevalence:>=0.01 AND site:1003 AND alt_base:G&fetch_all=true
GET https://dev.outbreak.info/wastewater_variants/query?scroll_id=FGluY2x1ZGVfY29udGV4dF91dWlkDXF1ZXJ5QW5kRmV0Y2gBFnNKbEd4cUZSVEEtOXdfRy1JVV8tMmcAAAAAACEf5hZHV0dfbkk2elNUS2dCdTI1dzA4T3F3&fetch_all=true&page=0&fetch_all=true

                    alt_base  depth  prevalence ref_base  site sra_accession
mutation
1003 AND alt_base:G        G    158    0.018426        A  1003   SRR22720076
1003 AND alt_base:G        G     21    0.078358        A  1003   SRR26775757
1003 AND alt_base:G        G    216    0.051811        A  1003   SRR21095540
1003 AND alt_base:G        G   2708    0.024436        A  1003   SRR27050417
1003 AND alt_base:G        G     51    0.038088        A  1003   SRR21864715
...                      ...    ...         ...      ...   ...           ...
1003 AND alt_base:G        G     71    0.010667        A  1003   SRR27996879
1003 AND alt_base:G        G     24    0.011516        A  1003   SRR29083918
1003 AND alt_base:G        G     74    0.015198        A  1003   SRR28346158
1003 AND alt_base:G        G    761    0.016743        A  1003   SRR28852794
1003 AND alt_base:G        G    230    0.018639        A  1003   SRR29647926

[69 rows x 6 columns]